version: "3" # version of docker compose to use
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev # dockerfile to use to create an image
      context: ./nginx
    ports:
      - '3050:80' # local machine: inside container
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev # dockerfile to use to create an image
      context: ./server # where files to come from
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis   # sync with line number 12
      - REDIS_PORT=6379    # default port
      - PGUSER=postgres
      - PGHOST=postgres    # service name line no 10
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev # dockerfile to use to create an image
      context: ./client # where files to come from
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev # dockerfile to use to create an image
      context: ./worker # where files to come from
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


